//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTwitterStatusReader.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TweetData", Namespace="http://schemas.datacontract.org/2004/07/WcfStatusReaderService")]
    [System.SerializableAttribute()]
    public partial class TweetData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TweetStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeStamp {
            get {
                return this.DateTimeStampField;
            }
            set {
                if ((this.DateTimeStampField.Equals(value) != true)) {
                    this.DateTimeStampField = value;
                    this.RaisePropertyChanged("DateTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TweetStatus {
            get {
                return this.TweetStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TweetStatusField, value) != true)) {
                    this.TweetStatusField = value;
                    this.RaisePropertyChanged("TweetStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStatusContract")]
    public interface IStatusContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTweets", ReplyAction="http://tempuri.org/IStatusContract/GetTweetsResponse")]
        string GetTweets(int tweets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTweets", ReplyAction="http://tempuri.org/IStatusContract/GetTweetsResponse")]
        System.Threading.Tasks.Task<string> GetTweetsAsync(int tweets);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTweetData", ReplyAction="http://tempuri.org/IStatusContract/GetTweetDataResponse")]
        WpfTwitterStatusReader.ServiceReference1.TweetData GetTweetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTweetData", ReplyAction="http://tempuri.org/IStatusContract/GetTweetDataResponse")]
        System.Threading.Tasks.Task<WpfTwitterStatusReader.ServiceReference1.TweetData> GetTweetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTop10Tweets", ReplyAction="http://tempuri.org/IStatusContract/GetTop10TweetsResponse")]
        string GetTop10Tweets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatusContract/GetTop10Tweets", ReplyAction="http://tempuri.org/IStatusContract/GetTop10TweetsResponse")]
        System.Threading.Tasks.Task<string> GetTop10TweetsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatusContractChannel : WpfTwitterStatusReader.ServiceReference1.IStatusContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatusContractClient : System.ServiceModel.ClientBase<WpfTwitterStatusReader.ServiceReference1.IStatusContract>, WpfTwitterStatusReader.ServiceReference1.IStatusContract {
        
        public StatusContractClient() {
        }
        
        public StatusContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatusContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatusContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTweets(int tweets) {
            return base.Channel.GetTweets(tweets);
        }
        
        public System.Threading.Tasks.Task<string> GetTweetsAsync(int tweets) {
            return base.Channel.GetTweetsAsync(tweets);
        }
        
        public WpfTwitterStatusReader.ServiceReference1.TweetData GetTweetData() {
            return base.Channel.GetTweetData();
        }
        
        public System.Threading.Tasks.Task<WpfTwitterStatusReader.ServiceReference1.TweetData> GetTweetDataAsync() {
            return base.Channel.GetTweetDataAsync();
        }
        
        public string GetTop10Tweets() {
            return base.Channel.GetTop10Tweets();
        }
        
        public System.Threading.Tasks.Task<string> GetTop10TweetsAsync() {
            return base.Channel.GetTop10TweetsAsync();
        }
    }
}
